### ISSUE TITLE
Translation: Bower: зачем фронтенду нужен менеджер пакетов

### ISSUE THREAD

**Issue by varya** [frontendbabel/frontendbabel.github.com#17]
http://nano.sapegin.ru/all/bower

```
author:
  name: Artem Sapegin
  site: http://blog.sapegin.me/
  twitter: iamsapegin
  github: sapegin
```
