### ISSUE TITLE
Translation: Про @viewport

### ISSUE THREAD

**Issue by varya** [frontendbabel/frontendbabel.github.com#86]
http://wd.dizaina.net/internet-maintenance/about-viewport-at-rule/

```
author:
  name: Oleg Korsunsky
  site: http://wd.dizaina.net/en/
  github: wilddeer
  twitter: wildir
```
